# Generated by Django 2.1.3 on 2018-11-22 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('registrated', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('rating', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['-rating'],
                'verbose_name': 'Профиль пользователя',
            },
        ),
    ]
