# Generated by Django 2.1.3 on 2018-12-16 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_imagepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст')),
                ('com_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки комментария')),
                ('answer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='profiles.Comment', verbose_name='Ответ на комментарий')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to_this_post', to='profiles.Post', verbose_name='Прокомментированный пост')),
            ],
        ),
        migrations.AlterModelOptions(
            name='imagepost',
            options={'verbose_name': 'Картинка поста', 'verbose_name_plural': 'Картинки постов'},
        ),
    ]
