# Generated by Django 2.1.3 on 2018-12-19 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20181216_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comment_images/')),
            ],
            options={
                'verbose_name_plural': 'Картинки комментариев',
                'verbose_name': 'Картинка комментария',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['com_date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='answer_to',
        ),
        migrations.AddField(
            model_name='imagecomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='profiles.Comment', verbose_name='Коммент'),
        ),
    ]
