# Generated by Django 2.1.3 on 2018-12-20 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20181219_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='profiles.Post', verbose_name='Репост'),
        ),
    ]
