# Generated by Django 2.1.3 on 2018-12-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_post_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_repost',
            field=models.BooleanField(default=False, verbose_name='Является репостом'),
        ),
    ]
