# Generated by Django 2.1.3 on 2018-11-30 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название чата')),
                ('create_data', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_group', models.BooleanField()),
                ('member', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Участник чата')),
            ],
            options={
                'verbose_name_plural': 'Чаты',
                'ordering': ['create_data'],
                'verbose_name': 'Чат',
            },
        ),
    ]
