# Generated by Django 2.1.3 on 2018-11-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='member',
            new_name='members',
        ),
    ]
